image: astait/flutter_linux_build:master

stages:
  - build

build:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - flutter pub get
    - flutter build linux
  artifacts:
    paths:
    - build/
