image: astait/flutter_linux_build:0.3.0

stages:
  - build

build:
  stage: build
  only:
    - tags
    - triggers
    - schedules
    - web
  script:
    - flutter channel dev
    - flutter upgrade
    - flutter pub get
    - flutter build linux
  artifacts:
    paths:
    - build/linux/release
