name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.6.6+1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0
  #postgres: ^2.1.0
  mysql1:
    git: https://github.com/leontappe/mysql1_dart.git
    #path: ../mysql1_dart
  package_info: ^2.0.0
  pdf: ^3.0.1
  image: ^3.0.1
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  crypto: ^3.0.0
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  file_picker: ^3.0.0
  autocomplete_textfield: ^1.7.3
  csv: ^4.1.0
  archive: ^3.1.2
  windows_documents: ^0.0.1
  logging: ^1.0.0
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
