name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  sqflite_common_ffi: ^1.0.0+1
  #postgres: ^2.1.0
  mysql1: ^0.17.1
  package_info: ^0.4.0+16
  pdf: ^1.5.0
  image: ^2.1.4
  meta: ^1.1.8
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  crypto: ^2.1.4
  path_provider: ^1.6.5
  path_provider_macos: ^0.0.4
  path_provider_fde:
    git:
      url: git://github.com/leontappe/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
    #path: ../path_provider_fde
  file_chooser:
    git:
      url: git://github.com/leontappe/flutter-desktop-embedding.git
      path: plugins/file_chooser
    #path: ../file_chooser

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
