name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.4.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  sqflite: ^1.3.1+1
  sqflite_common_ffi: ^1.1.0+1
  #postgres: ^2.1.0
  mysql1: ^0.17.1
  package_info: ^0.4.3
  pdf: ^1.11.1
  image: ^2.1.15
  meta: ^1.2.3
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  crypto: ^2.1.5
  path_provider: ^1.6.14
  path_provider_macos: ^0.0.4+4
  path_provider_fde:
    git:
      url: git://github.com/leontappe/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/path_provider_fde
    #path: ../path_provider_fde
  file_chooser:
    git:
      url: git://github.com/leontappe/flutter-desktop-embedding.git
      path: plugins/file_chooser
    #path: ../file_chooser
  autocomplete_textfield: ^1.7.3
  csv: ^4.0.3
  archive: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
