name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.9.0
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  #postgres: ^2.1.0
  mysql1: ^0.19.2
  package_info: ^2.0.2
  pdf: ^3.4.2
  image: ^3.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  path_provider: ^2.0.2
  path_provider_macos: ^2.0.2
  file_picker: ^4.0.0
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2+1
  file_selector_macos: ^0.0.4+1
  file_selector_linux: ^0.0.2+1
  autocomplete_textfield: ^1.7.3
  csv: ^5.0.0
  archive: ^3.1.2
  windows_documents: ^1.0.0
  logging: ^1.0.1
  uuid: ^3.0.4
  clipboard: ^0.1.3
  open_file: ^3.2.1
  sentry_flutter: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
