name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.10.0+1
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  #postgres: ^2.1.0
  mysql1: ^0.19.2
  package_info_plus: ^1.4.0
  pdf: ^3.4.2
  image: ^3.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  path_provider: ^2.0.9
  file_picker: ^4.0.0
  file_selector: ^0.8.4+1
  autocomplete_textfield: ^1.7.3
  csv: ^5.0.0
  archive: ^3.1.2
  windows_documents: ^1.0.0
  logging: ^1.0.1
  uuid: ^3.0.4
  clipboard: ^0.1.3
  open_file: ^3.2.1
  sentry_flutter: ^5.1.0
  path_provider_platform_interface: ^2.0.0
  asta_theme:
    git: https://git.upb.de/asta/asta_theme.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  uses-material-design: true
