name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.8.0
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  sqflite: ^2.0.0+2
  sqflite_common_ffi: ^2.0.0
  #postgres: ^2.1.0
  mysql1: ^0.17.1
    #git: https://github.com/leontappe/mysql1_dart.git
    #path: ../mysql1_dart
  package_info: ^2.0.0
  pdf: ^2.1.0
  image: ^2.1.19
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  crypto: ">=0.9.2 <3.0.0"
  path_provider: ^2.0.1
  path_provider_macos: ^2.0.0
  file_picker: ^3.0.0
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_linux: ^0.0.2
  autocomplete_textfield: ^1.7.3
  csv: ^5.0.0
  archive: ^2.0.13
  windows_documents: ^1.0.0
  logging: ^0.11.4
  uuid: ^2.2.2
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
