name: bitter
authors:
  - Leon Tappe <ltappe@mail.upb.de>
description: A billing app with interchangeable database, customer management and PDF output
version: 0.5.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  sqflite: ^1.3.1+1
  sqflite_common_ffi: ^1.1.0+1
  #postgres: ^2.1.0
  mysql1: ^0.17.1
  package_info: ^0.4.3
  pdf: ^1.11.1
  image: ^2.1.15
  meta: ^1.2.3
  bloc: ^6.0.3
  flutter_bloc: ^6.1.0
  crypto: ^2.1.5
  path_provider: ^1.6.15
  path_provider_macos: ^0.0.4+4
  file_picker_cross: ^4.2.2
  autocomplete_textfield: ^1.7.3
  csv: ^4.0.3
  archive: ^2.0.13
  windows_documents: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
